site_name: datar
theme:
    # favicon: favicon.png
    # logo: favicon.png
    # palette:
    #   primary: blue
    name: 'material'
    # font:
    #   text: 'Ubuntu'
    #   code: 'Ubuntu Mono'
markdown_extensions:
    - markdown.extensions.admonition
    - pymdownx.superfences:
        preserve_tabs: true
    - toc:
        baselevel: 2
plugins:
    - search # necessary for search to work
    - mkapi
    - mkdocs-jupyter:
        execute: True
extra_css:
    - style.css
nav:
    - 'Home': 'index.md'
    - 'API': 'mkapi/api/datar'
    - 'Examples':
        'across': 'notebooks/across.ipynb'
        'arrange': 'notebooks/arrange.ipynb'
        'desc': 'notebooks/desc.ipynb'
    - 'Change Log': CHANGELOG.md
