site_name: datar
theme:
    # favicon: favicon.png
    # logo: favicon.png
    # palette:
    #   primary: blue
    name: 'material'
    # font:
    #   text: 'Ubuntu'
    #   code: 'Ubuntu Mono'
markdown_extensions:
    - markdown.extensions.admonition
    - pymdownx.superfences:
        preserve_tabs: true
    - toc:
        baselevel: 2
plugins:
    - search # necessary for search to work
    - mkapi
    - mkdocs-jupyter:
        execute: false
extra_css:
    - style.css
nav:
    - 'Home': 'index.md'
    - 'API': 'mkapi/api/datar'
    - 'Examples':
        'across': 'notebooks/across.ipynb'
        'arrange': 'notebooks/arrange.ipynb'
        'base': 'notebooks/base.ipynb'
        'between': 'notebooks/between.ipynb'
        'bind': 'notebooks/bind.ipynb'
        'case_when': 'notebooks/case_when.ipynb'
        'coalesce': 'notebooks/coalesce.ipynb'
        'context': 'notebooks/context.ipynb'
        'count': 'notebooks/count.ipynb'
        'cumall': 'notebooks/cumall.ipynb'
        'desc': 'notebooks/desc.ipynb'
        'distinct': 'notebooks/distinct.ipynb'
        'drop_na': 'notebooks/drop_na.ipynb'
        'expand': 'notebooks/expand.ipynb'
        'expand_grid': 'notebooks/expand_grid.ipynb'
        'extract': 'notebooks/extract.ipynb'
        'fill': 'notebooks/fill.ipynb'
        'filter-joins': 'notebooks/filter-joins.ipynb'
        'full_seq': 'notebooks/full_seq.ipynb'
        'get': 'notebooks/get.ipynb'
        'group_by': 'notebooks/group_by.ipynb'
        'group_map': 'notebooks/group_map.ipynb'
        'group_split': 'notebooks/group_split.ipynb'
        'group_trim': 'notebooks/group_trim.ipynb'
        'lead-lag': 'notebooks/lead-lag.ipynb'
        'mutate-joins': 'notebooks/mutate-joins.ipynb'
        'mutate': 'notebooks/mutate.ipynb'
        'n_distinct': 'notebooks/n_distinct.ipynb'
        'na_if': 'notebooks/na_if.ipynb'
        'near': 'notebooks/near.ipynb'
        'nest-join': 'notebooks/nest-join.ipynb'
        'nth': 'notebooks/nth.ipynb'
        'pivot_longer': 'notebooks/pivot_longer.ipynb'
        'pivot_wider': 'notebooks/pivot_wider.ipynb'
        'pull': 'notebooks/pull.ipynb'
        'ranking': 'notebooks/ranking.ipynb'
        'readme': 'notebooks/readme.ipynb'
        'recode': 'notebooks/recode.ipynb'
        'relocate': 'notebooks/relocate.ipynb'
        'rename': 'notebooks/rename.ipynb'
        'replace_na': 'notebooks/replace_na.ipynb'
        'rowwise': 'notebooks/rowwise.ipynb'
        'select': 'notebooks/select.ipynb'
        'separate': 'notebooks/separate.ipynb'
        'setops': 'notebooks/setops.ipynb'
        'slice': 'notebooks/slice.ipynb'
        'summarise': 'notebooks/summarise.ipynb'
        'tibble': 'notebooks/tibble.ipynb'
        'uncount': 'notebooks/uncount.ipynb'
        'unite': 'notebooks/unite.ipynb'
        'with_groups': 'notebooks/with_groups.ipynb'
    - 'Change Log': CHANGELOG.md
