[tool.poetry]
name = "plyrda"
version = "0.0.1"
description = "Probably the closest port of tidyr + dplyr in python"
authors = ["pwwang <pwwang@pwwang.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pipda = "*"
modkit = "*"
pandas = "^1.1.4"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"
pytest-cov = "^2.10.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
